# This pipeline relies on the analysis.yml template located in the
# repository resource descibed below
resources:
  repositories:
  - repository: templates
    type: github
    endpoint: Team1-Project3
    name: 1053-August-Duet-Project-Registry/project-registry-devops
    ref: refs/heads/feature-templates

# This pipeline will trigger on commits or pull-requests made to the branch-dev
# or main branches.  Note that static analysis with SonarCloud is only performed
# on "long-lived" branches, which are designated as 'main' and any branch name
# prefixed with 'branch-'.
trigger:
- branch-dev
- main
pr:
- branch-dev
- main

pool:
  vmImage: ubuntu-latest

# These variable groups are required for sonarCloud and Discord secrets to be
# available in the analysis template
# The contents of these groups that are used here are:
#  project-registry-sonarcloud: stores sonarcloud variables/secrets
#   - sonarKeyPrefix: the common prefix string for the sonar keys in the project
#       (requires a sonarCloud project key)
#   - sonarNamePrefix: the common prefix string for the project names
#   - sonarOrg: the sonar organization
#   - sonarUrlPrefix: the common prefix string for the url for the results
#  project-registry-discord: stores discord variables/secrets
#   - discordAnalysisChannel: the output channel for discord analysis info
#   - discordAnalysisKey: the webhook key associated with the above channel

variables:
- group: project-registry-sonarcloud
- group: project-registry-discord

stages:
- stage: build
  jobs:
  - job: analyze

    steps:
    - checkout: self
    - checkout: templates
    - template: ./templates/analysis.yml@templates
      parameters:
        microservice: frontend
        workDir: project-registry-frontend/

    displayName: Analyze --> Job

    # Dockerize job goes here

  displayName: Build --> Stage
